services:
  app:
    container_name: example-ui-profile
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      CI: 'true'
    stdin_open: true
    env_file:
      - .env.development
